#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

/* Convert an integer in a certain base to a string */
char* itoa(int value, char* str, int base)
{
   bool is_negative = false;
   size_t i = 0;

   /* Only base 10 numbers are considered signed */
   if(base == 10 && value < 0) {
      is_negative = true;
      value = -value;
   }

   /* Use the utoa function to prevent duplicate code */
   char str_u[16];
   utoa((unsigned) value, str_u, base);

   if(is_negative) {
      str[i] = '-';
      ++i;
   }

   /* Copy the string generated by utoa to str */
   for(size_t j = 0; str_u[j] != '\0'; ++j, ++i)
      str[i] = str_u[j];
   
   return str;
}
